# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.UI'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 620)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 70, 101, 51))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 200, 71, 31))
        self.label_2.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(160, 200, 261, 31))
        self.email.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(243, 243, 243);")
        self.email.setObjectName("email")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 320, 91, 31))
        self.label_3.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(160, 320, 261, 31))
        self.password.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(243, 243, 243);")
        self.password.setText("")
        self.password.setObjectName("password")
        self.loginbutton = QtWidgets.QPushButton(Dialog)
        self.loginbutton.setGeometry(QtCore.QRect(210, 470, 111, 41))
        self.loginbutton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.loginbutton.setObjectName("loginbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "Email:"))
        self.label_3.setText(_translate("Dialog", "Password:"))
        self.loginbutton.setText(_translate("Dialog", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
